# Generated by Django 4.1.3 on 2022-11-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projects_author_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('DEV', 'DEV'), ('Designer', 'Designer'), ('Chef de project', 'Chef de project'), ('Lead', 'Lead')], max_length=255),
        ),
    ]
