# Generated by Django 4.1.3 on 2022-11-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contributors_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('L', 'FAIBLE'), ('M', 'MOYENNE'), ('H', 'ÉLEVÉE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('DO', 'À faire'), ('IN PROGRESS', 'En cours'), ('FINISH', 'Terminé')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('BUG', 'BUG'), ('AMÉLIORATION', 'AMÉLIORATION'), ('TÂCHE', 'TÂCHE')], max_length=255),
        ),
    ]
